use_frameworks!

target 'UXMBatchDownloader_Example' do
  pod 'UXMBatchDownloader', :path => '../'

  target 'UXMBatchDownloader_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
