use_frameworks!

target 'UXMBatchDownloader_Example' do
  pod 'UXMBatchDownloader', :path => '../'

  target 'UXMBatchDownloader_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
